../src/design/controler.v
../src/design/fpga_top_with_uart.v
../src/design/lenet/add.v
../src/design/lenet/convPoo1.v
../src/design/lenet/convPool2.v
../src/design/lenet/conv_mul_add_array.v
../src/design/lenet/fc.v
../src/design/lenet/fcMacArray.v
../src/design/lenet/fcRes_classify.v
../src/design/lenet/lenetTop.v
../src/design/lenet/mul.v
../src/design/lenet/mul25_4convolutor.v
../src/design/lenet/mul7_4.v
../src/design/lenet/multi.v
../src/design/lenet/reluPool.v
../src/design/lenet/reluPoolcov2.v
../src/design/sramArray.v
../src/design/uart_codec/rx_buffer.v
../src/design/uart_codec/tx_buffer.v
../src/design/uart_codec/uart_codec_top.v
../src/design/uart_codec/uart_rx.v
../src/design/uart_codec/uart_tx.v
../src/flash_read/data_concat.v
../src/flash_read/data_loader_top.v
../src/flash_read/data_load_ctrl.v
../src/flash_read/flash_read_ctrl.v
../src/flash_read/key_filter.v
../src/sram/sram464x144.v
../src/sram/sram520x104.v
../tb/uart_rx_tb.v
../tb/v_model/W25Q128JVxIM.v
